"""create market price observations

Revision ID: 69aad5b8074f
Revises: 
Create Date: 2026-08-24 16:35:06.158754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69aad5b8074f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('product_line', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=False),
    sa.Column('cpu', sa.String(length=150), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_capacity_gb', sa.Integer(), nullable=False),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('source_reliability', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition IN ('new', 'used', 'refurbished')", name='ck_market_observation_condition'),
    sa.CheckConstraint("storage_type IN ('ssd', 'hdd', 'emmc', 'unknown')", name='ck_market_observation_storage_type'),
    sa.CheckConstraint('quantity > 0', name='ck_market_observation_quantity_positive'),
    sa.CheckConstraint('ram_gb > 0', name='ck_market_observation_ram_positive'),
    sa.CheckConstraint('source_reliability >= 0 AND source_reliability <= 1', name='ck_market_observation_reliability_range'),
    sa.CheckConstraint('storage_capacity_gb > 0', name='ck_market_observation_storage_positive'),
    sa.CheckConstraint('unit_price > 0', name='ck_market_observation_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_observation_comparable_lookup', 'market_price_observations', ['manufacturer', 'model_number', 'ram_gb', 'storage_capacity_gb', 'condition', 'observation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_observation_comparable_lookup', table_name='market_price_observations')
    op.drop_table('market_price_observations')
    # ### end Alembic commands ###
