"""track market observation freshness

Revision ID: a781872ff33b
Revises: eef7e294b169
Create Date: 2026-08-25 16:36:19.036002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a781872ff33b'
down_revision: Union[str, Sequence[str], None] = 'eef7e294b169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_price_observations', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_price_observations', 'last_seen_at')
    # ### end Alembic commands ###
