"""add source observation deduplication

Revision ID: eef7e294b169
Revises: 69aad5b8074f
Create Date: 2026-08-25 15:26:50.509487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef7e294b169'
down_revision: Union[str, Sequence[str], None] = '69aad5b8074f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_price_observations', sa.Column('source_external_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_market_observation_source_daily', 'market_price_observations', ['source_name', 'source_external_id', 'observation_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_observation_source_daily', 'market_price_observations', type_='unique')
    op.drop_column('market_price_observations', 'source_external_id')
    # ### end Alembic commands ###
